version: '3.1'

services:
  springboot:
    image: akareem225/spring-boot-mongo:latest
    restart: always
    container_name: springboot
    ports:
      - 9090:8080
    working_dir: /opt/app
    depends_on:
      - mongo
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 20s
      restart_policy:
        condition: on-failure   

  mongo:
    image: mongo
    container_name: mongo
    ports:   
      - 27018:27017
    volumes:
      - ebsvolume:/data/db
    restart: always
    
volumes:
  #data:
    #external: true
  ebsvolume:
    driver: rexray/ebs
    external: true
    
networks:
  default:
    external:
      name: customoverlay
